version: '2'
services:
  api:
    build: .
    volumes:
      - .:/go/src/first-project
    ports:
      - 8080:8080 # API server
    depends_on:
      - postgres
    environment: # pass through environments for build / test purposes
      - GO_ENV
    depends_on:
      - postgres
  postgres:
    image: postgres:11.3
    environment: 
      POSTGRES_PASSWORD: mysecret
      POSTGRES_DB: first_project_db
  adminer:
    image: adminer:latest
    ports:
      - 3655:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres
